### ISSUE TITLE
disroot email is probably open soruce

### ISSUE THREAD

**Issue by advait404** [Lissy93/email-comparison#12]
Hi, i noticed that the disroot email is not considered FOSS. It says that they use [https://roundcube.net/](https://roundcube.net/) in the backend, which is open source. This may need an update, or I might be overlooking something.

Thanks a LOT for making this wonderful list. it has been really helpful in finding the right email service provider.

**Comment by Lissy93** [comment]
Roundcube is the client used, so that's more the frontend rather than backend
